version: "3.7"
services:
  nginx:
    build: .
    container_name: nginx-proxy
    networks:
      - nginx_proxy_net
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    environment:
      - TZ=Asia/Seoul
    restart: always
  certbot:
    image: certbot/certbot:latest
    command: certonly --webroot --webroot-path=/var/lib/letsencrypt --email jintea519@gmail.com --agree-tos --no-eff-email -d cigmacode.com -d www.cigmacode.com -d k8a601.p.ssafy.io
    restart: always
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt

networks:
  nginx_proxy_net:
    external: true
