version: "3.7"
services:
  nginx:
    container_name: nginx-proxy
    image: nginx:latest
    networks:
      - nginx_proxy_net
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./cigma/dist:/var/www/html
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - ./nginx/default.conf/etc/nginx/sites-enabled/default.conf
    restart: always

networks:
  nginx_proxy_net:
    external: true
