version: "3.7"
services:
  nginx:
    build: .
    container_name: nginx-proxy
    networks:
      - nginx_proxy_net
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    environment:
      - TZ=Asia/Seoul
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx-ingress.rule=Host(`cigmacode.com`)"
      - "traefik.http.routers.nginx-ingress.service=nginx"
    restart: always

networks:
  nginx_proxy_net:
    external: true
