version: "3.7"
services:
  nginx:
    build: .
    container_name: nginx-proxy
    networks:
      - nginx_proxy_net
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    environment:
      - TZ=Asia/Seoul
    restart: always
  certbot:
    container_name: certbot
    image: certbot/certbot:v0.36.0
    restart: always
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt

networks:
  nginx_proxy_net:
    external: true
