version: "3.7"
services:
  nginx:
    container_name: nginx-proxy
    image: nginx:latest
    networks:
      - nginx_proxy_net
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/default-conf:/etc/nginx
      - ./cigma/dist:/var/www/html
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
    restart: always

networks:
  nginx_proxy_net:
    external: true
