version: "3.7"
services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    networks:
      - nginx_proxy_net
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/default-conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./cigma/dist:/var/www/html
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    restart: always

networks:
  nginx_proxy_net:
    external: true
