# SERVER
server:
  port: 9090
  servlet:
    context-path: /api

# DB
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # server
    url: jdbc:mysql://k8a601.p.ssafy.io:3306/cigma?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    # local
#    url: jdbc:mysql://127.0.0.1:3306/cigma?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ssafy
    password: ssafy
    hikari:
      idle-timeout: 10000
      maximum-pool-size: 10
      minimum-idle: 5
  jpa:
    defer-datasource-initialization: true
    database: mysql
    hibernate:
      ddl-auto: update
    generate-ddl: false
    properties:
      hibernate:
        #        SQL ??? ??? ????? ???
        format_sql: true
        #
        show-sql: true
        #
        use_sql_comments: true

  ## redis 설정
  # RDB와 AOF를 동시에 사용
  # - redis 실행 시에는 스냅샷을 통해 불러오기
  # - redis 실행 중에는 AOF를 사용하여 기록
  # - redis 종료 시에는 RDB를 통해 스냅샷 생성

  redis:
#    host: localhost # localhost 전용
    host: redis # Server 전용
    port: 6379
    password: ssafy8cigmapass

# log level ??
logging:
  level:
    org:
      # security log level ??
      springframework:
        security: DEBUG
      # hibernate log level ??
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: trace
    # ???? ???? ??.
    # AWS
    com:
      amazonaws:
        util:
          EC2MetadataUtils: ERROR

# jwt 관련
jwt:
  header: Authorization
  secret: Y2lnbWEtc3ByaW5nLWJvb3Qtand0LXNlY3JldC1rZXktY2lnbWEtc3ByaW5nLWJvb3Qtand0LXNlY3JldC1rZXktYnktYWpoCg==
  access-token-validity-in-seconds: 1800000 # accessToken 유효시간 30분
#  access-token-validity-in-seconds: 10000 # accessToken 유효시간 10초
  refresh-token-validity-in-seconds: 1209600000 # refreshToken 유효시간 2주

# aws 관련
cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket: cigma-ajh
    access-key: AKIA3WSTMVY32SWQLEFQ
    secret-key: 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
    stack:
      auto: false

# image 관련
image:
  base-path:
    user: Users/Image/
    team: Teams/Image/
    project: Projects/Image/
  default-path:
    user: https://cigma-ajh.s3.ap-northeast-2.amazonaws.com/Users/Image/default.png
    team: https://cigma-ajh.s3.ap-northeast-2.amazonaws.com/Teams/Image/default.png
    project: https://cigma-ajh.s3.ap-northeast-2.amazonaws.com/Projects/Image/default.png