version: "3.7"
services:
  nginx:
    container_name: nginx-proxy
    image: nginx:latest
    networks:
      - nginx_proxy_net
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/nginx/nginx.conf:./nginx.conf
      - /var/www/html:../cigma/dist
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - /etc/nginx/sites-enabled/default.conf:./default.conf
    restart: always

networks:
  nginx_proxy_net:
    external: true
